### PR TITLE
Feature/relay workaround string ids

### PR DESCRIPTION
**Pull request by lowsky**
Hi Clay,

I had strange, subtle errors while using Relay with the Github schema _containing integer Ids_.

The only hint I found about that was on these Relay pages:

https://facebook.github.io/relay/docs/graphql-object-identification.html
or
https://facebook.github.io/relay/graphql/objectidentification.htm
### Details:

When the GithubUser had an id of type GraphQLInt, which results in a graphql result
of an **integer id:**

```
{
"user": { "id": 153704 }
}
```

the relay client fails with 

```
dataID.startsWith is not a function
```

WOOT!  - it just expects a String (which has a startsWith function) 

---

As a workaround I just convert it to a string in the JSON response, which solved my problem :-)

Thanks for integrating this change!

-This changes are done on top of #34 
, so you may need to first apply that pull request -

### CODE REVIEW

**Comment by clayallsopp** [comment]
This would make it work, but I'm hesitant to merge because the Github GraphQL bindings really don't support Relay at all except by coincidence (such as in this proposed case). I.e. there's no top-level `node(id)` field, none of the types conform to `Node`, the pagination isn't idiomatic, etc

I'd be excited about a new, separate Github schema that is Relay-compatible from the start (similar to what we did for Hacker News https://github.com/clayallsopp/graphqlhub/pull/28), but worried that coercing IDs will just be a hack and break other code that assumes the IDs are integers =\

**Comment by lowsky** [comment]
I understand your concerns. 
Compatibility for client/server in different versions might get difficult in our case, it may easily break things.
That is imho the unclear issue about graphql to me: _How to migrate in a safe way?_

Do you have any hints for me or 
do you know some blogs/documentation about how serve schemas in different versions?

... in the meantime, I will have a look into #28 for getting an idea, and could try a relay-compatible version from scratch.

You can close this request.

**Comment by clayallsopp** [comment]
@lowsky if you check #28, we added a new schema field `hn2` which is completely separate from the original, non-Relay `hn` one. I'd suggest doing this similarly - having a new `github2` field and set of schemas

**Comment by lowsky** [comment]
Hi @clayallsopp - I was planning to create such a relay-compatible Github Schema.
But after GitHub announced and published their own graphql API interface, I do not plan to create a specific, unofficial API! 
That wont make sense to me.
And thanks for developing graphqlhub, anyway!

**Pull request closed without merging**
